angular.module("lorienIpsum", ['ngAudio'])
    .controller("Main", ["$scope", function($scope, $filter) {
        var elvishSayingsAndMeanings = [
            "'Ksherea",
            "Evil ones",
            "'Kshonna, wanya",
            "Dispel",
            "'Kshonnarim, wanya",
            "Mass Dispel",
            "'Quel re amrun undome",
            "Good day morning evening",
            "A'maelamin",
            "My beloved",
            "A!",
            "Ah!",
            "Aa' i'sul nora lanne'lle",
            "May the wind fill your sails",
            "Aa' lasser en lle coia orn n' omenta gurtha",
            "May the leaves of your life tree never turn brown",
            "Aa' menealle nauva calen ar' malta",
            "May your ways be green and golden",
            "Aa' menle nauva calen ar' ta hwesta e' ale'quenle",
            "May thy paths be green and the breeze on thy back",
            "Aaye",
            "Hail",
            "Agaryulnaerea",
            "Blood-suckers",
            "Ai' atar",
            "Little father An adult male dwarf",
            "Aierea",
            "Short ones",
            "Aiya!",
            "Oh!",
            "Alduya",
            "Thursday",
            "Ale' amin lye tela sinome",
            "After I we finish here",
            "Ama handasse",
            "Cunning",
            "Ama poldora",
            "Strength",
            "Ama tyelka",
            "Agility",
            "Aman tel' Seldarine",
            "Bless",
            "Amandil",
            "Cleric",
            "Amandil",
            "Priest",
            "amin",
            "I, my, mine",
            "Amin uuma merna ta",
            "I don't want it",
            "Amin anta est kaim",
            "I need to rest sleep",
            "Amin autien rath",
            "I'm going to bed",
            "Amin caela noa n'noa",
            "I have an idea no idea",
            "Amin dele ten' ho he sen",
            "I am worried about him her them",
            "Amin delotha lle",
            "I hate you",
            "Amin fauka",
            "I am thirsty",
            "Amin feuya ten' lle",
            "You disgust me",
            "Amin harmuva onalle e' cormamin",
            "I shall treasure your gift in my heart",
            "Amin hiraetha",
            "I'm sorry",
            "Amin irma fion laure sereg",
            "I would like some wine mead ale",
            "Amin khiluva lle a' gurtha ar' thar",
            "I will follow you to death and beyond",
            "Amin lava",
            "I yield",
            "Amin mela lle",
            "I love you",
            "Amin merna quen",
            "I wish to speak",
            "Amin n'rangwa edanea",
            "I don't understand these humans",
            "Amin naa lle nai",
            "I am yours to command",
            "Amin naa tualle",
            "I am your servant",
            "Amin nauva auta yeste'",
            "I will go first",
            "Amin nowe ron n'kelaya",
            "I thought they would never leave",
            "amin quella",
            "invisibility",
            "Amin saesa",
            "My pleasure",
            "Amin sinta lle?",
            "Do I know you?",
            "Amin sinta thaliolle e dagor",
            "I know your strength in battle",
            "Amin utue ta",
            "I found it",
            "Amin uuma malia",
            "I don't care",
            "amin vasa lle sinta",
            "feeblemind",
            "Amin weera yassen lle",
            "I agree with you",
            "Amrun'quessir",
            "Sunrise elf",
            "An lema?",
            "Long journey?",
            "Anarya",
            "Tuesday",
            "Andodulin",
            "Gate birdslain enemy",
            "Anthatal",
            "Nightsedge Watchfull City",
            "Antolle ulua sulrim",
            "Much wind pours from your mouth",
            "Aratoamin",
            "My champion",
            "Arwen en amin",
            "My lady non familiar",
            "Arwenamin",
            "My lady familiar",
            "Asca",
            "Hurry",
            "asca melloneamin",
            "Haste",
            "Ascarerea",
            "Impetous ones",
            "Astalderea",
            "Valiant ones",
            "Atost en' entula orme",
            "Reactive Armor",
            "Auta miqula orqu",
            "Go kiss an orc",
            "Avarierea",
            "Unwilling ones",
            "Beikaerea",
            "Excessive ones",
            "Bela ed' templa",
            "Telekinesis",
            "Belegerea",
            "Mighty ones",
            "bragol alaa",
            "enlarge",
            "bragol thalion",
            "strength",
            "Bragollach en' templa",
            "Explosion",
            "bragollach tel'llach",
            "Fireball",
            "Caela ie'lle",
            "Have at thee!",
            "Cairbara",
            "Port Llast Ship Dwelling",
            "Cala'quessir",
            "High elf",
            "Cam'wethrin",
            "Thief",
            "Caran Pinnath",
            "Red Larch Red Ridges",
            "Cermie",
            "July",
            "Cormamin lindua ele lle",
            "My heart sings to see thee",
            "Cormamin niuve tenna' ta elea lle au'",
            "My heart shall weep until it sees thee again",
            "Cormlle naa tanya tel'raa",
            "Your heart is that of the lion",
            "Creoso a'baramin",
            "Welcome to my dwelling",
            "Creoso, mellonamin",
            "Welcome my friend",
            "Cuamin linduva yassen megrille",
            "My bow will sing with your sword",
            "Dagnir en taur'ohtar",
            "Berun Ranger's Bane",
            "Desiel?",
            "Ready?",
            "Detholalle",
            "Your choice",
            "Dina",
            "Be silent",
            "Dinaerea",
            "Silent ones",
            "Diola lle",
            "Thank you",
            "Dolle naa lost",
            "Your head is empty",
            "Ear'quessir",
            "Sea elf",
            "Ed' i'ear ar' elenea!",
            "By the sea and stars!",
            "Edan",
            "Human",
            "Ehtele'mele",
            "Vernal Equinox",
            "Ela sen",
            "Flank them",
            "Elandili",
            "Half-elf",
            "Elea i'dolen",
            "Reveal",
            "Elea ie' dome",
            "Night Sight",
            "Elear",
            "Visionary",
            "Elen sila lumenn omentilmo",
            "A star shall shine on the hour of our meeting",
            "Elenya",
            "Monday",
            "En!",
            "Look!",
            "Engwarerea",
            "Ill ones",
            "Entula a' moinayamen'",
            "Recall",
            "Entula en' templa",
            "Magic Reflection",
            "Entula tuulo' i'ba",
            "Resurrection",
            "Esta sinome",
            "Rest here",
            "Estolada sinome",
            "Camp here",
            "Faina templa",
            "Energy Bolt",
            "Faradome",
            "Summer Solstace",
            "Feuyaerea",
            "Disgusting ones",
            "For",
            "North",
            "Gayaerea",
            "Dreaded ones",
            "Glamhoth",
            "Orc",
            "Gorgaerea",
            "Fearful ones",
            "gorgamin",
            "fear",
            "Goth en gothamin",
            "Foe of my foe",
            "Gothrimamin",
            "My foes",
            "Guinahiroo",
            "Undead Lords UDL",
            "Gurth gothrim Tel' Mithrim",
            "Death to the foes of the Grey Company",
            "Gurth gothrim Tel'Quessir",
            "Death to the foes of the Elves",
            "Gurth gothrimlye",
            "Death to our foes",
            "Hallaerea",
            "Tall ones",
            "Hama sinome",
            "Have a seat",
            "Har",
            "South",
            "Harnram",
            "Southwall",
            "he",
            "her, hers",
            "Helkaerea",
            "Icy ones",
            "Heru en amin",
            "My lord non familiar",
            "Heruamin",
            "My lord familiar",
            "Hisime",
            "November",
            "ho",
            "him, his",
            "Hodoerea",
            "Wise ones",
            "Hyandae en' luhta",
            "Blade Spirits",
            "I'narr en gothrim glinuva nuin I'anor",
            "The bones of our foes will gleam under the sun",
            "I'quelin Mori'Quessier naa ba Mori'Quessir",
            "The best Drow is a dead Drow",
            "Ianterea",
            "Old ones",
            "Iire lye lle auta?",
            "When do we you leave?",
            "Iire?",
            "When?",
            "irma haeannon",
            "dimension door",
            "Isilya",
            "Wednesday",
            "Istar",
            "Wizard",
            "Ita'istar",
            "Illusionist",
            "Ithil'quessir",
            "Moon elf",
            "karn aduamin",
            "mirror image",
            "Kela",
            "Go away",
            "khelek hurro'",
            "ice storm",
            "Kheleksii",
            "Luskan Icy Beach",
            "Khila amin",
            "Follow me",
            "Kiirar",
            "Chronicler",
            "Koron en' naur",
            "Fireball",
            "Kotyaerea",
            "Hostile ones",
            "Kwara sina ten'amin",
            "Hold this for me",
            "Kwentra lye i'narn",
            "Tell us the tale",
            "Laara'tincoras",
            "Clan Axepeak Flat Metal",
            "Lannerea",
            "Wide ones",
            "lanta en' kalale",
            "lightning bolt",
            "lanta kaima",
            "sleep",
            "Lasta lalaithamin",
            "Listen to my laughter",
            "Lema ed' ando en' templa",
            "Gate Travel",
            "Lema ed' templa",
            "Teleport",
            "lietha guldur",
            "dispel magic",
            "Lindar",
            "Bard",
            "Lirimaerea",
            "Lovely ones",
            "Lissenen ar' maska'lalaith tenna' lye omentuva",
            "Sweet water and light laughter till next we meet",
            "lle",
            "you, yours",
            "Lle anta amin tu?",
            "Do you need help?",
            "Lle anta yulna en alu?",
            "Do you need a drink of water?",
            "Lle auta yeste'",
            "You go first",
            "Lle creoso",
            "You're welcome",
            "Lle desiel?",
            "Are you ready?",
            "Lle holma ve' edan",
            "You smell like a human",
            "Lle ista amin quella no' amin?",
            "Could you cast invis on me?",
            "Lle lakwenien?",
            "Are you joking?",
            "Lle lava?",
            "Do you yield?",
            "Lle maa quel",
            "You look good",
            "Lle merna aut farien?",
            "Shall we go hunting?",
            "Lle merna salk?",
            "Do you want to dance?",
            "Lle naa belegohtar",
            "You are a mighty warrior",
            "Lle naa curucuar",
            "You are a skillful bowman",
            "Lle naa haran e' nausalle",
            "You are king in your imagination",
            "Lle naa vanima",
            "You are beautiful",
            "lle quella",
            "invisibility 10'",
            "Lle quena i'lambe tel' Eldalie?",
            "Do you speak elvish?",
            "Lle rangwa amin?",
            "Do you understand me?",
            "Lle tela?",
            "Are you finished?",
            "Lle tyava quel?",
            "Do you feel well?",
            "Lle ume quel",
            "You did well",
            "Lle vesta?",
            "Do you promise?",
            "Lle wethrine amin",
            "You deceived me",
            "llie",
            "you, yours plural",
            "Llie n'vanima ar' lle atara lanneina",
            "You're ugly and your mother dresses you funny",
            "loomi en gurth",
            "cloudkill",
            "loomi tanya lirva amin",
            "stinking cloud",
            "Lotesse",
            "May",
            "Lova handasse",
            "Feeblemind",
            "Lova poldora",
            "Weaken",
            "Lova termara en' templa",
            "Mana Drain",
            "Lova tyelka",
            "Clumsy",
            "Luhta kanta",
            "Polymorph",
            "lye",
            "we, us, ours",
            "Lye naa lle nai",
            "We are yours to command",
            "Lye nuquernuva sen e dagor",
            "We will defeat them in battle",
            "Mae govannen",
            "Well met",
            "Maien quel n'quel",
            "Looking good bad",
            "Malia ten' fion laure sereg?",
            "Care for some wine mead ale?",
            "Malia ten' vasa?",
            "Care for some food?",
            "Malia ten' yulna?",
            "Care for a drink?",
            "Mallen pelu e' n'alaquel en' sen",
            "Circle around behind them",
            "Mani er?",
            "Which one?",
            "Mani marte?",
            "What happened?",
            "Mani naa essa en lle?",
            "What's your name?",
            "Mani naa lle umien?",
            "What are you doing?",
            "Mani naa ta?",
            "What is it?",
            "Mani naa tanya nat'?",
            "What is that thing?",
            "Mani nae lle umien?",
            "What have you been doing?",
            "Mani uma lle merna ten' ta?",
            "What do you want for it?",
            "Mani ume lle quena?",
            "What did you say?",
            "Mani?",
            "What?",
            "Manka lle merna",
            "If you wish",
            "Manke naa nae lle llie lye tuulo'?",
            "Where are were you you all we from?",
            "Manke naa nae lle?",
            "Where are were you?",
            "Manke naa lye lle autien?",
            "Where are we you going?",
            "Manke naa i'omentien?",
            "Where is the meeting?",
            "Manke naa lye omentien?",
            "Where are we meeting?",
            "Manke tanya tuula?",
            "Where did that come from?",
            "Manke?",
            "Where?",
            "Mankoi lle irma sint?",
            "Why do you want to know?",
            "Mankoi lle uma tanya?",
            "Why did you do that?",
            "Mankoi naa lle sinome?",
            "Why are you here?",
            "Mankoi?",
            "Why?",
            "Megiltura",
            "Swordmaster",
            "Mela en' coiamin",
            "Love of my life",
            "Melamin",
            "My love",
            "Mellon en mellonamin",
            "Friend of my friend",
            "Mellonea",
            "Friends",
            "Mellonamin",
            "My friend",
            "Melloneamin",
            "My friends",
            "Men imya ram en' templa",
            "Dispel Field",
            "Menelya",
            "Friday",
            "Menomenta",
            "Crossergate Path Crossing",
            "Mereth en draugrim",
            "Feast of wolves slain enemy",
            "Mith'quessir",
            "Gray elf",
            "Mith'quessir",
            "Silver elf",
            "Mori'quessir",
            "Drow When indicating respect",
            "Morierea",
            "Dark ones",
            "Morimaikarea",
            "KAAOS Dark demi-gods",
            "Morsul",
            "The Black Wind ITB",
            "N'hrive",
            "Neverwinter",
            "N'ndengina ta ho",
            "Don't kill it him",
            "n'tess gothamin",
            "hold person",
            "n'tess uuvanimo",
            "hold monster",
            "naar cam",
            "burning hands",
            "Nadorhuanrim",
            "Cowardly dogs",
            "Nae saian luume'",
            "It has been too long",
            "nai turamin",
            "charm person",
            "nai uuvanimo turamin",
            "charm monster",
            "Namaarie",
            "Farewell",
            "Nandaror",
            "The Harpers HG",
            "Narie",
            "June",
            "Narquelie",
            "October",
            "Narvinye",
            "January",
            "Naugiaur",
            "Westbridge Dwarf Bridge",
            "Naugrim",
            "Dwarf",
            "naur tinchor ostring",
            "fire shield cold",
            "naur tinchor osturra",
            "fire shield hot",
            "Ndengina ta ho",
            "Kill it him",
            "Nenime",
            "February",
            "Neuma en' templa",
            "Magic Trap",
            "Neuma!",
            "Trap!",
            "Nikerym",
            "Captain",
            "Nim'ohtar",
            "Paladin",
            "Nogoth",
            "Gnome",
            "Nogoth",
            "Gnome",
            "Nuduin",
            "Floodblest Under River",
            "Numen",
            "West",
            "Nurta",
            "Hide",
            "Nurta I' fea",
            "Incognito",
            "Nwalmaerea",
            "Tormented ones",
            "Ohtar",
            "Warrior",
            "Ohtar en Oionaaru",
            "Knights of the Eternal Flame KEF",
            "Oio naa elealla alasse'",
            "Ever is thy sight a joy",
            "Ona ta a'amin",
            "Give it to me",
            "Onta vasa",
            "Create Food",
            "Panta tangwa",
            "Unlock",
            "parm templa tengwa",
            "read magic",
            "Pela en' bela templa",
            "Energy Vortex",
            "pela tanya tempa aiguldur",
            "minor globe",
            "Pelekta yassen I' handele",
            "Mind Blast",
            "Pelekta yassen runya",
            "Flamestrike",
            "Peredhil",
            "Halfling",
            "Pilin en' templa",
            "Magic Arrow",
            "Poika tel' taurninin",
            "Archcure",
            "Poika tuulo' 'kshapsae",
            "Cure",
            "Poikaerea",
            "Pure ones",
            "Qualohtarie",
            "Grey Knights of the Balance Neutral warriors",
            "Quanta yassen 'kshapsa",
            "Poison",
            "Quel andune",
            "Good afternoon",
            "Quel du",
            "Good night",
            "Quel esta",
            "Rest well",
            "Quel fara",
            "Good hunting",
            "Quel kaima",
            "Sleep well",
            "Quel lome",
            "Good evening Farewell",
            "Quel marth",
            "Good luck",
            "Quel re",
            "Good day",
            "Quel undome",
            "Good evening Greeting",
            "Quella tuulo' elea",
            "Invisibility",
            "Rah'edan",
            "Centaur",
            "Ram en' 'kshapsa",
            "Poison Field",
            "Ram en' naur",
            "Fire Field",
            "Ram en' ondo",
            "Wall of Stone",
            "Ram en' templa",
            "Energy Field",
            "Ram en' tessa",
            "Paralyze Field",
            "re",
            "she",
            "Re caele beika fion laure sereg",
            "She had too much wine mead ale",
            "Rhun",
            "East",
            "Rima ten'ta!",
            "Run for it!",
            "Rina istorlle sinome",
            "Memorize your spells here",
            "ring wing",
            "cone of cold",
            "Ringare",
            "December",
            "ro",
            "he",
            "Ro caele beika fion laure sereg",
            "He had too much wine mead ale",
            "ron",
            "they",
            "Ron rangwa amin?",
            "Do they understand me?",
            "Runyalanta gonea",
            "Meteor Swarm",
            "Russe tuulo' moriloomir",
            "Lightning",
            "Ruthaerea",
            "Angry ones",
            "rwalaerea",
            "Lusty ones",
            "Saesa omentien lle",
            "Pleasure meeting you",
            "Sana sina",
            "Take this",
            "Sana termara en' templa",
            "Mana Vampire",
            "Saurarea",
            "Foul ones",
            "Seasamin",
            "My pleasure",
            "sen",
            "them, their",
            "Sereg'wethrin",
            "Assassin",
            "Shaalth",
            "Lieutenant",
            "Sheelala",
            "Spring Festival",
            "Sii'",
            "Now!",
            "Silmataurea",
            "Neverwinter Woods Starlit woods",
            "sina",
            "this",
            "Soora sen ta",
            "Follow them it",
            "Spangaerea",
            "Bearded ones",
            "Sulcabedoo",
            "Windycliffes",
            "Sulime",
            "March",
            "Sut an?",
            "How long?",
            "Sut naa lle umien sina re?",
            "How are you doing today?",
            "Sut?",
            "How?",
            "ta",
            "it, its",
            "Ta naa nae seasamin",
            "It is was my pleasure",
            "Ta naa neuma!",
            "It is a trap!",
            "Ta naa seasamin",
            "It is my pleasure",
            "Tal Dagore",
            "Triboar City of Battle",
            "Tampa tanya!",
            "Stop that!",
            "Tangwa en' templa",
            "Magic Lock",
            "Tanka harwar",
            "Heal",
            "Tanka tel' taurnin",
            "Greater Heal",
            "tanya",
            "that",
            "Tanya awra!",
            "That hurt!",
            "Tanya farnuva",
            "That will suffice",
            "Tanya nae sai eina",
            "That was very funny",
            "Tanya nae n'quel",
            "That was not good",
            "Taraerea",
            "Lofty ones",
            "Tarion",
            "Sunday",
            "Taur'amandil",
            "Druid",
            "Taur'ohtar",
            "Ranger",
            "Taur'quessir",
            "Sylvan elf",
            "Tel'Anor Arator",
            "The Sun Guild Sun Champions",
            "Tel'Domeduathea",
            "The Night Masks",
            "Tel'Mithrim",
            "The Grey Company",
            "Tel'Ranaemyn",
            "The Lost Hills The Wandering Hills",
            "Tel'Sindavathar",
            "The Shadow AllianceThe Grey Shadows",
            "Tel'gothrim",
            "Drow Normal",
            "Telcoerea",
            "Stern ones",
            "Templa en' tessa",
            "Paralyze",
            "templa pilini'",
            "Magic missile",
            "Tenna' ento lye omenta",
            "Until next we meet",
            "Tenna' san'",
            "Until then",
            "Tenna' telwan san'",
            "Until later then",
            "Tenna' tul're san'",
            "Until tomorrow then",
            "Tessa sina ten' amin",
            "Hold onto this for me",
            "Thanga yassen templa",
            "Curse",
            "Thangarim yassen templa",
            "Mass Curse",
            "Thaurerea",
            "Abominable ones",
            "Tincokemen",
            "Vilnask Metal Soil",
            "Tincya en' russe tuulo' moriloomir",
            "Chain Lightning",
            "tinechor",
            "shield",
            "Tintila, kemen",
            "Earthquake",
            "Tira ten' rashwe!",
            "Look out   Be carefull!",
            "Tolea' Fuin",
            "Neverwinter Islands Isles of Gloom",
            "Toror' Taur'ohtarie",
            "Brotherhood of Pathfinders",
            "Tua amin!",
            "Help me!",
            "Tula Uialtum",
            "Come to Longsaddle",
            "Tula sinome",
            "Come here",
            "Tula, hama neva i'naur",
            "Come, sit near the fire",
            "Tula, vasa ar' yulna en i'mereth",
            "Come, eat and drink of the feast",
            "Tulien",
            "Coming",
            "Tyara harwar",
            "Harm",
            "Tyela neuma",
            "Magic Untrap",
            "Uialtum",
            "Longsaddle Twilight Valley",
            "Unguerea",
            "Hollow ones",
            "Urime",
            "August",
            "Usquenerea",
            "Smelly ones",
            "Utinu en lokirim",
            "Son of snakes dishonest person",
            "Uuma dela",
            "Don't worry",
            "Uuma ma' ten' rashwe, ta tuluva a' lle",
            "Don't look for trouble, it will come to you",
            "Uuner uma, n'dela no'ta",
            "No one does, don't worry about it",
            "Val'istar",
            "Archmage",
            "Valanya",
            "Saturday",
            "Vanimle sila tiri",
            "Your beauty shines bright",
            "Vanya sulie",
            "Fair winds",
            "Vara tel' Seldarine",
            "Protection",
            "Vara tel' taurninin",
            "Archprotection",
            "Vedui' il'er",
            "Greetings everyone",
            "Viresse",
            "April",
            "Voronwerea",
            "Loyal ones",
            "Waenen",
            "Sewers Stained Water",
            "Wethrinaerea",
            "Deceitfull ones",
            "Ya naa nae tanya?",
            "Who is was that?",
            "Ya auta yeste'?",
            "Who's leading?",
            "Ya?",
            "Who?",
            "Yaaraerea",
            "Ancient ones",
            "Yala onna",
            "Summon Creature",
            "Yala onna en' alu",
            "Summon Water Elemental",
            "Yala onna en' kemen",
            "Summon Earth Elemental",
            "Yala onna en' naur",
            "Summon Fire Elemental",
            "Yala onna en' vilya",
            "Summon Air Elemental",
            "Yala rauko",
            "Summon Daemon",
            "Yallume",
            "At last!",
            "Yavannie",
            "September",
            "Yavieba",
            "Autumnal Equinox",
            "Yee!",
            "Eek!",
            "Yenearsira",
            "Winter Solstice",
            "Yulma ten' lemar en' templa",
            "Mark"
        ];

        var sayings = [];
        var meanings = [];
        var sentencesPerParagraph = 8;
        var particlesPerSentence = 4;
        var paragraphCount = 3;

        var randomness = 0;

        $scope.options = {
          paragraphs:3,
          sentences:5,
          language: 'elvish'
        };

        // var dictionary = [];

        for (var i = 0; i < elvishSayingsAndMeanings.length; i++) {
            var thing = elvishSayingsAndMeanings[i];
            if (i % 2) {
                sayings.push(elvishSayingsAndMeanings[i]);
            } else {
                meanings.push(elvishSayingsAndMeanings[i]);
            }
        };

        var sayingPairs = _.zip(sayings, meanings);
        sayingPairs = sayingPairs.filter(function(pair) {
            return pair[0] && pair[1];
        }).map(function(pair) {
            return {
                english: pair[0],
                elvish: pair[1],
            }
        })

        $scope.run = function(options) {

          if (!options) options = $scope.options;
          var _paragraphs = options.paragraphs;
          var _sentences = options.sentences;
          // var 

            function capitaliseFirstLetter(string) {
                return string.charAt(0).toUpperCase() + string.slice(1);
            }

            function containsPunctuation(string) {
               return string.match(/[?.]/);
            }

            function getLastLetter(string) {
              var lastLetter = string.charAt(string.length - 1);
              return lastLetter;
            }

            function containsSpace(string) {
               return string.match(/[\s]/);
            }

            function random() {
              return Math.floor(Math.random() * randomness);
            }

            $scope.paragraphs = [];
            for (var i = 0; i < _paragraphs + random(); i++) {
                var paragraph = [];
                for (var j = 0; j < _sentences + random(); j++) {
                    var sentence = []
                    for (var k = 0; k < particlesPerSentence + random(); k++) {
                        var particle = _.sample(sayingPairs);
                        sentence.push(particle);
                    };

                    sentence = _.uniq(sentence);
                    sentence = sentence.map(function(val, index) {
                        saying = _.clone(val);
                        if (index === 0) {
                            saying.elvish = capitaliseFirstLetter(saying.elvish);
                            saying.english = capitaliseFirstLetter(saying.english);
                        } else if (saying.elvish.match(/[\s]/)) {
                            saying.elvish = saying.elvish.toLowerCase();
                            saying.english = saying.english.toLowerCase();
                        }

                        if (index != sentence.length - 1) {

                            if (containsPunctuation(getLastLetter(saying.elvish))) {
                                saying.elvish = saying.elvish.substring(0, saying.elvish.length - 1);
                                saying.english = saying.english.substring(0, saying.english.length - 1);
                            }

                            saying.elvish = saying.elvish + " ";
                            saying.english = saying.english + " ";

                        } else if (!containsPunctuation(saying.elvish)) {
                            saying.elvish = saying.elvish + ".";
                            saying.english = saying.english + ".";
                        }



                        return saying;
                    })
                    paragraph.push(sentence);
                };

                paragraph = _.uniq(paragraph);
                $scope.paragraphs.push(paragraph);
            }
        };

        $scope.run();





    }]);
