angular.module("lorienIpsum", [])
.controller("Main",function($scope){
	var elvishSayingsAndMeanings = [
   "A star shall shine on the hour of our meeting",
   "Elen sila lumenn omentilmo",
   "Good",
   "'Quel",
   "Greetings everyone",
   "Vedui' il'er",
   "Hail",
   "Aaye",
   "It has been too long",
   "Nae saian luume'",
   "My heart sings to see thee",
   "Cormamin lindua ele lle",
   "Pleasure meeting you",
   "Saesa omentien lle",
   "Well met",
   "Mae govannen",
  "Fair winds",
  "Vanya sulie",
  "Farewell",
  "Namaarie",
  "Good day afternoon evening night",
  "Quel re andune lome du",
  "Good hunting",
  "Quel fara",
  "May the leaves of your life tree never turn brown",
  "Aa' lasser en lle coia orn n' omenta gurtha",
  "May the wind fill your sails",
  "Aa' i'sul nora lanne'lle",
  "May thy paths be green and the breeze on thy back",
  "Aa' menle nauva calen ar' ta hwesta e' ale'quenle",
  "May your ways be green and golden",
  "Aa' menealle nauva calen ar' malta",
  "My heart shall weep until it sees thee again",
  "Cormamin niuve tenna' ta elea lle au'",
  "Rest well",
  "Quel esta",
  "Sleep well",
  "Quel kaima",
  "Sweet water and light laughter till next we meet",
  "Lissenen ar' maska'lalaith tenna' lye omentuva",
  "Until later then",
  "Tenna' telwan san'",
  "Until next we meet",
  "Tenna' ento lye omenta",
  "Until then",
  "Tenna' san'",
  "Until tomorrow then",
  "Tenna' tul're san'",
  "Ever is thy sight a joy",
  "Oio naa elealla alasse'",
  "You are a mighty warrior",
  "Lle naa belegohtar",
  "You are a skillful bowman",
  "Lle naa curucuar",
  "You are beautiful",
  "Lle naa vanima",
  "You did well",
  "Lle ume quel",
  "You look good",
  "Lle maa quel",
  "Your beauty shines bright",
  "Vanimle sila tiri",
  "Your heart is that of the lion",
  "Cormlle naa tanya tel'raa",
  "Cowardly dogs",
  "Nadorhuanrim",
  "Feast of wolves slain enemy",
  "Mereth en draugrim",
  "Gate birdslain enemy",
  "Andodulin",
  "Go kiss an orc",
  "Auta miqula orqu",
  "I hate you",
  "Amin delotha lle",
  "Listen to my laughter",
  "Lasta lalaithamin",
  "Much wind pours from your mouth",
  "Antolle ulua sulrim",
  "Son of snakes dishonest person",
  "Utinu en lokirim",
  "You are king in your imagination",
  "Lle naa haran e' nausalle",
  "You disgust me",
  "Amin feuya ten' lle",
  "You smell like a human",
  "Lle holma ve' edan",
  "You're ugly and your mother dresses you funny",
  "Llie n'vanima ar' lle atara lanneina",
  "Your head is empty",
  "Dolle naa lost",
  "Are you finished?",
  "Lle tela?",
  "Are you joking?",
  "Lle lakwenien?",
  "Are you ready?",
  "Lle desiel?",
  "Care for a drink some food?",
  "Malia ten' yulna vasa?",
  "Care for some wine mead ale?",
  "Malia ten' fion laure sereg?",
  "Could you cast invis on me?",
  "Lle ista amin quella no' amin?",
  "Do you they understand me?",
  "Lle Ron rangwa amin?",
  "Do I know you?",
  "Amin sinta lle?",
  "Do you feel well?",
  "Lle tyava quel?",
  "Do you need a drink of water?",
  "Lle anta yulna en alu?",
  "Do you need help?",
  "Lle anta amin tu?",
  "Do you promise?",
  "Lle vesta?",
  "Do you speak elvish?",
  "Lle quena i'lambe tel' Eldalie?",
  "Do you want to dance?",
  "Lle merna salk?",
  "Do you yield?",
  "Lle lava?",
  "How are you doing today?",
  "Sut naa lle umien sina re?",
  "How long?",
  "Sut an?",
  "How?",
  "Sut?",
  "Long journey?",
  "An lema?",
  "Shall we go hunting?",
  "Lle merna aut farien?",
  "What's your name?",
  "Mani naa essa en lle?",
  "What are you doing?",
  "Mani naa lle umien?",
  "What did you say?",
  "Mani ume lle quena?",
  "What do you want for it?",
  "Mani uma lle merna ten' ta?",
  "What happened?",
  "Mani marte?",
  "What have you been doing?",
  "Mani nae lle umien?",
  "What is it?",
  "Mani naa ta?",
  "What is that thing?",
  "Mani naa tanya nat'?",
  "What?",
  "Mani?",
  "When do we you leave?",
  "Iire lye lle auta?",
  "When?",
  "Iire?",
  "Where are were you you all we from?",
  "Manke naa nae lle llie lye tuulo'?",
  "Where are were you?",
  "Manke naa nae lle?",
  "Where are we you going?",
  "Manke naa lye lle autien?",
  "Where are we meeting?",
  "Manke naa lye omentien?",
  "Where did that come from?",
  "Manke tanya tuula?",
  "Where is the meeting?",
  "Manke naa i'omentien?",
  "Where?",
  "Manke?",
  "Which one?",
  "Mani er?",
  "Who's leading?",
  "Ya auta yeste'?",
  "Who is was that?",
  "Ya naa nae tanya?",
  "Who?",
  "Ya?",
  "Why are you here?",
  "Mankoi naa lle sinome?",
  "Why did you do that?",
  "Mankoi lle uma tanya?",
  "Why do you want to know?",
  "Mankoi lle irma sint?",
  "Why?",
  "Mankoi?",
  "Ah!",
  "A!",
  "At last!",
  "Yallume!",
  "By the sea and stars!",
  "Ed' i'ear ar' elenea!",
  "Eek!",
  "Yee!",
  "Help me!",
  "Tua amin!",
  "It is a trap!",
  "Ta naa neuma!",
  "Look!",
  "En!",
  "Now!",
  "Sii'!",
  "Oh!",
  "Aiya!",
  "Run for it!",
  "Rima ten'ta!",
  "Stop that!",
  "Tampa tanya!",
  "That hurt!",
  "Tanya awra!",
  "Be silent",
  "Dina",
  "Camp here",
  "Estolada sinome",
  "Circle around behind them",
  "Mallen pelu e' n'alaquel en' sen",
  "Come here",
  "Tula sinome",
  "Come to Longsaddle",
  "Tula Uialtum",
  "Come, sit near the fire",
  "Tula, hama neva i'naur",
  "Don't kill it him",
  "N'ndengina ta ho",
  "Don't worry",
  "Uuma dela",
  "Flank them",
  "Ela sen",
  "Follow them it",
  "Soora sen ta",
  "Follow me",
  "Khila amin",
  "Give it to me",
  "Ona ta a'amin",
  "Go away",
  "Kela",
  "Hide",
  "Nurta",
  "Hold onto this for me",
  "Tessa sina ten' amin",
  "Hurry",
  "Asca",
  "Kill it him",
  "Ndengina ta ho",
  "Look out   Be carefull!",
  "Tira ten' rashwe!",
  "Memorize your spells here",
  "Rina istorlle sinome",
  "Rest here",
  "Esta sinome",
  "Take this",
  "Sana sina",
  "Tell us the tale",
  "Kwentra lye i'narn",
  "You go first",
  "Lle auta yeste'",
  "He She had too much wine mead ale",
  "Ro Re caele beika fion laure sereg",
  "I we am yours to command",
  "Amin Lye naa lle nai",
  "It was my pleasure",
  "Ta nae amin saesa",
  "After I we finish here",
  "Ale' amin lye tela sinome",
  "Come, eat and drink of the feast",
  "Tula, vasa ar' yulna en i'mereth",
  "Coming",
  "Tulien",
  "Don't look for trouble, it will come to you",
  "Uuma ma' ten' rashwe, ta tuluva a' lle",
  "Good luck",
  "Quel marth",
  "Have a seat",
  "Hama sinome",
  "Hold this for me",
  "Kwara sina ten'amin",
  "I'm going to bed",
  "Amin autien rath",
  "I'm sorry",
  "Amin hiraetha",
  "I don't want it",
  "Amin uuma merna ta",
  "I agree with you",
  "Amin weera yassen lle",
  "I am thirsty",
  "Amin fauka",
  "I am worried about them",
  "Amin dele ten' ho",
  "I am your servant",
  "Amin naa tualle",
  "I don't care",
  "Amin uuma malia",
  "I don't understand these humans",
  "Amin n'rangwa edanea",
  "I found it",
  "Amin utue ta",
  "I have an idea no idea",
  "Amin caela noa n'noa",
  "I know your strength in battle",
  "Amin sinta thaliolle e dagor",
  "I love you",
  "Amin mela lle",
  "I need to sleep",
  "Amin anta kaim",
  "I shall treasure your gift in my heart",
  "Amin harmuva onalle e' cormamin",
  "I thought they would never leave",
  "Amin nowe ron n'kelaya",
  "I will go first",
  "Amin nauva auta yeste'",
  "I wish to speak",
  "Amin merna quen",
  "I would like some",
  "Amin irma",
  "I yield",
  "Amin lava",
  "If you wish",
  "Manka lle merna",
  "It was my pleasure",
  "Ta nae seasamin",
  "Looking good",
  "Maien quel",
  "My bow shall sing with your sword",
  "Cuamin linduva yassen megrille",
  "My pleasure",
  "Seasamin",
  "No one does, don't worry about it",
  "Uuner uma, n'dela no'ta",
  "Thank you",
  "Diola lle",
  "That was funny",
  "Tanya nae eina",
  "That was not good",
  "Tanya nae n'quel",
  "That will suffice",
  "Tanya farnuva",
  "The best Drow is a dead Drow",
  "I'quelin Mori'Quessier naa ba Mori'Quessir",
  "The bones of our foes will gleam under the sun",
  "I'narr en gothrim glinuva nuin I'anor",
  "We will defeat them in battle",
  "Lye nuquernuva sen e dagor",
  "Welcome my friend",
  "Creoso, mellonamin",
  "Welcome to my dwelling",
  "Creoso a'baramin",
  "You're welcome",
  "Lle creoso",
  "You deceived me",
  "Lle wethrine amin",
  "Your choice",
  "Detholalle"];

  var sayings = [];
  var meanings = [];

  for (var i =0; i < elvishSayingsAndMeanings.length;i++) {
  	var thing = elvishSayingsAndMeanings[i];
  	if (i % 2) {
  		sayings.push(elvishSayingsAndMeanings[i]);
  	} else {
  		meanings.push(elvishSayingsAndMeanings[i]);
  	}
  };

  var sayingPairs = _.zip(sayings,meanings);

  $scope.run = function(paragraphCount) {

  	var sentencesPerParagraph = 24

  	paragraphCount = paragraphCount || 5;
  	$scope.paragraphs = [];
  	for (var i = 0; i < paragraphCount; i++ ) {
  		var paragraph = [];
  		for (var j = sentencesPerParagraph - 1; j >= 0; j--) {
  			var sentence = _.sample(sayingPairs);
  			paragraph.push(sentence);
  		};

  		paragraph = _.uniq(paragraph);

  		$scope.paragraphs.push(paragraph);
  	}

  	return _.sample(sayings,15).join(" ");
  };

  $scope.run();





})