angular.module("lorienIpsum", ['ngAudio'])
.controller("Main",["$scope",function($scope){
	var elvishSayingsAndMeanings = [
   "  A star shall shine on the hour of our meeting",
"Elen sila lumenn omentilmo",
"Good day morning afternoon evening",
"'Quel re amrun andune undome",
"Greetings everyone",
"Vedui' il'er",
"Hail",
"Aaye",
"It has been too long",
"Nae saian luume'",
"My heart sings to see thee",
"Cormamin lindua ele lle",
"Pleasure meeting you",
"Saesa omentien lle",
"Well met",
"Mae govannen",
" Fair winds",
"Vanya sulie",
"Farewell",
"Namaarie",
"Good day afternoon evening night",
"Quel re andune lome du",
"Good hunting",
"Quel fara",
"May the leaves of your life tree never turn brown",
"Aa' lasser en lle coia orn n' omenta gurtha",
"May the wind fill your sails",
"Aa' i'sul nora lanne'lle",
"May thy paths be green and the breeze on thy back",
"Aa' menle nauva calen ar' ta hwesta e' ale'quenle",
"May your ways be green and golden",
"Aa' menealle nauva calen ar' malta",
"My heart shall weep until it sees thee again",
"Cormamin niuve tenna' ta elea lle au'",
"Rest well",
"Quel esta",
"Sleep well",
"Quel kaima",
"Sweet water and light laughter till next we meet",
"Lissenen ar' maska'lalaith tenna' lye omentuva",
"Until later then",
"Tenna' telwan san'",
"Until next we meet",
"Tenna' ento lye omenta",
"Until then",
"Tenna' san'",
"Until tomorrow then",
"Tenna' tul're san'",
" Ever is thy sight a joy",
"Oio naa elealla alasse'",
"You are a mighty warrior",
"Lle naa belegohtar",
"You are a skillful bowman",
"Lle naa curucuar",
"You are beautiful",
"Lle naa vanima",
"You did well",
"Lle ume quel",
"You look good",
"Lle maa quel",
"Your beauty shines bright",
"Vanimle sila tiri",
"Your heart is that of the lion",
"Cormlle naa tanya tel'raa",
" Cowardly dogs",
"Nadorhuanrim",
"Feast of wolves slain enemy",
"Mereth en draugrim",
"Gate birdslain enemy",
"Andodulin",
"Go kiss an orc",
"Auta miqula orqu",
"I hate you",
"Amin delotha lle",
"Listen to my laughter",
"Lasta lalaithamin",
"Much wind pours from your mouth",
"Antolle ulua sulrim",
"Son of snakes dishonest person",
"Utinu en lokirim",
"You are king in your imagination",
"Lle naa haran e' nausalle",
"You disgust me",
"Amin feuya ten' lle",
"You smell like a human",
"Lle holma ve' edan",
"You're ugly and your mother dresses you funny",
"Llie n'vanima ar' lle atara lanneina",
"Your head is empty",
"Dolle naa lost",
" Are you finished?",
"Lle tela?",
"Are you joking?",
"Lle lakwenien?",
"Are you ready?",
"Lle desiel?",
"Care for a drink some food?",
"Malia ten' yulna vasa?",
"Care for some wine mead ale?",
"Malia ten' fion laure sereg?",
"Could you cast invis on me?",
"Lle ista amin quella no' amin?",
"Do you they understand me?",
"Lle Ron rangwa amin?",
"Do I know you?",
"Amin sinta lle?",
"Do you feel well?",
"Lle tyava quel?",
"Do you need a drink of water?",
"Lle anta yulna en alu?",
"Do you need help?",
"Lle anta amin tu?",
"Do you promise?",
"Lle vesta?",
"Do you speak elvish?",
"Lle quena i'lambe tel' Eldalie?",
"Do you want to dance?",
"Lle merna salk?",
"Do you yield?",
"Lle lava?",
"How are you doing today?",
"Sut naa lle umien sina re?",
"How long?",
"Sut an?",
"How?",
"Sut?",
"Long journey?",
"An lema?",
"Shall we go hunting?",
"Lle merna aut farien?",
"What's your name?",
"Mani naa essa en lle?",
"What are you doing?",
"Mani naa lle umien?",
"What did you say?",
"Mani ume lle quena?",
"What do you want for it?",
"Mani uma lle merna ten' ta?",
"What happened?",
"Mani marte?",
"What have you been doing?",
"Mani nae lle umien?",
"What is it?",
"Mani naa ta?",
"What is that thing?",
"Mani naa tanya nat'?",
"What?",
"Mani?",
"When do we you leave?",
"Iire lye lle auta?",
"When?",
"Iire?",
"Where are were you you all we from?",
"Manke naa nae lle llie lye tuulo'?",
"Where are were you?",
"Manke naa nae lle?",
"Where are we you going?",
"Manke naa lye lle autien?",
"Where are we meeting?",
"Manke naa lye omentien?",
"Where did that come from?",
"Manke tanya tuula?",
"Where is the meeting?",
"Manke naa i'omentien?",
"Where?",
"Manke?",
"Which one?",
"Mani er?",
"Who's leading?",
"Ya auta yeste'?",
"Who is was that?",
"Ya naa nae tanya?",
"Who?",
"Ya?",
"Why are you here?",
"Mankoi naa lle sinome?",
"Why did you do that?",
"Mankoi lle uma tanya?",
"Why do you want to know?",
"Mankoi lle irma sint?",
"Why?",
"Mankoi?",
" Ah!",
"A!",
"At last!",
"Yallume!",
"By the sea and stars!",
"Ed' i'ear ar' elenea!",
"Eek!",
"Yee!",
"Help me!",
"Tua amin!",
"It is a trap!",
"Ta naa neuma!",
"Look!",
"En!",
"Now!",
"Sii'!",
"Oh!",
"Aiya!",
"Run for it!",
"Rima ten'ta!",
"Stop that!",
"Tampa tanya!",
"That hurt!",
"Tanya awra!",
" Be silent",
"Dina",
"Camp here",
"Estolada sinome",
"Circle around behind them",
"Mallen pelu e' n'alaquel en' sen",
"Come here",
"Tula sinome",
"Come to Longsaddle",
"Tula Uialtum",
"Come, sit near the fire",
"Tula, hama neva i'naur",
"Don't kill it him",
"N'ndengina ta ho",
"Don't worry",
"Uuma dela",
"Flank them",
"Ela sen",
"Follow them it",
"Soora sen ta",
"Follow me",
"Khila amin",
"Give it to me",
"Ona ta a'amin",
"Go away",
"Kela",
"Hide",
"Nurta",
"Hold onto this for me",
"Tessa sina ten' amin",
"Hurry",
"Asca",
"Kill it him",
"Ndengina ta ho",
"Look out   Be carefull!",
"Tira ten' rashwe!",
"Memorize your spells here",
"Rina istorlle sinome",
"Rest here",
"Esta sinome",
"Take this",
"Sana sina",
"Tell us the tale",
"Kwentra lye i'narn",
"You go first",
"Lle auta yeste'",
" He She had too much wine mead ale",
"Ro Re caele beika fion laure sereg",
"I we am yours to command",
"Amin Lye naa lle nai",
"It was my pleasure",
"Ta nae amin saesa",
"After I we finish here",
"Ale' amin lye tela sinome",
"Come, eat and drink of the feast",
"Tula, vasa ar' yulna en i'mereth",
"Coming",
"Tulien",
"Don't look for trouble, it will come to you",
"Uuma ma' ten' rashwe, ta tuluva a' lle",
"Good luck",
"Quel marth",
"Have a seat",
"Hama sinome",
"Hold this for me",
"Kwara sina ten'amin",
"I'm going to bed",
"Amin autien rath",
"I'm sorry",
"Amin hiraetha",
"I don't want it",
"Amin uuma merna ta",
"I agree with you",
"Amin weera yassen lle",
"I am thirsty",
"Amin fauka",
"I am worried about him her them",
"Amin dele ten' ho he sen",
"I am your servant",
"Amin naa tualle",
"I don't care",
"Amin uuma malia",
"I don't understand these humans",
"Amin n'rangwa edanea",
"I found it",
"Amin utue ta",
"I have an idea no idea",
"Amin caela noa n'noa",
"I know your strength in battle",
"Amin sinta thaliolle e dagor",
"I love you",
"Amin mela lle",
"I need to rest sleep",
"Amin anta est kaim",
"I shall treasure your gift in my heart",
"Amin harmuva onalle e' cormamin",
"I thought they would never leave",
"Amin nowe ron n'kelaya",
"I will go first",
"Amin nauva auta yeste'",
"I wish to speak",
"Amin merna quen",
"I would like some wine mead ale",
"Amin irma fion laure sereg",
"I yield",
"Amin lava",
"If you wish",
"Manka lle merna",
"It is was my pleasure",
"Ta naa nae seasamin",
"Looking good bad",
"Maien quel n'quel",
"My bow shall sing with your sword",
"Cuamin linduva yassen megrille",
"My pleasure",
"Seasamin",
"No one does, don't worry about it",
"Uuner uma, n'dela no'ta",
"Thank you",
"Diola lle",
"That was very funny",
"Tanya nae sai eina",
"That was not good",
"Tanya nae n'quel",
"That will suffice",
"Tanya farnuva",
"The best Drow is a dead Drow",
"I'quelin Mori'Quessier naa ba Mori'Quessir",
"The bones of our foes will gleam under the sun",
"I'narr en gothrim glinuva nuin I'anor",
"We will defeat them in battle",
"Lye nuquernuva sen e dagor",
"Welcome my friend",
"Creoso, mellonamin",
"Welcome to my dwelling",
"Creoso a'baramin",
"You're welcome",
"Lle creoso",
"You deceived me",
"Lle wethrine amin",
"Your choice",
"Detholalle",
" Ancient ones",
"Yaaraerea",
"Bearded ones",
"Spangaerea",
"Foe of my foe",
"Goth en gothamin",
"Friend of my friend",
"Mellon en mellonamin",
"Friends",
"Mellonea",
"Little father An adult male dwarf",
"Ai' atar",
"Love of my life",
"Mela en' coiamin",
"Lovely ones",
"Lirimaerea",
"Loyal ones",
"Voronwerea",
"Lusty ones",
"rwalaerea",
"Mighty ones",
"Belegerea",
"My beloved",
"A'maelamin",
"My champion",
"Aratoamin",
"My friend",
"Mellonamin",
"My friends",
"Melloneamin",
"My lady familiar",
"Arwenamin",
"My lady non familiar",
"Arwen en amin",
"My lord familiar",
"Heruamin",
"My lord non familiar",
"Heru en amin",
"My love",
"Melamin",
"Pure ones",
"Poikaerea",
"Short ones",
"Aierea",
"Tall ones",
"Hallaerea",
"Valiant ones",
"Astalderea",
"Visionary",
"Elear",
"Wise ones",
"Hodoerea",
" Abominable ones",
"Thaurerea",
"Angry ones",
"Ruthaerea",
"Blood-suckers",
"Agaryulnaerea",
"Dark ones",
"Morierea",
"Deceitfull ones",
"Wethrinaerea",
"Disgusting ones",
"Feuyaerea",
"Dreaded ones",
"Gayaerea",
"Evil ones",
"'Ksherea",
"Excessive ones",
"Beikaerea",
"Fearful ones",
"Gorgaerea",
"Foul ones",
"Saurarea",
"Hollow ones",
"Unguerea",
"Hostile ones",
"Kotyaerea",
"Icy ones",
"Helkaerea",
"Ill ones",
"Engwarerea",
"Impetous ones",
"Ascarerea",
"Lofty ones",
"Taraerea",
"My foes",
"Gothrimamin",
"Old ones",
"Ianterea",
"Silent ones",
"Dinaerea",
"Smelly ones",
"Usquenerea",
"Stern ones",
"Telcoerea",
"Tormented ones",
"Nwalmaerea",
"Unwilling ones",
"Avarierea",
"Wide ones",
"Lannerea",
" Death to our foes",
"Gurth gothrimlye",
"Death to the foes of the Elves",
"Gurth gothrim Tel'Quessir",
"Death to the foes of the Grey Company",
"Gurth gothrim Tel' Mithrim",
"Have at thee!",
"Caela ie'lle",
"I will follow you to death and beyond",
"Amin khiluva lle a' gurtha ar' thar",
" Berun Ranger's Bane",
"Dagnir en taur'ohtar",
"Crossergate Path Crossing",
"Menomenta",
"Floodblest Under River",
"Nuduin",
"Longsaddle Twilight Valley",
"Uialtum",
"Luskan Icy Beach",
"Kheleksii",
"Neverwinter",
"N'hrive",
"Neverwinter Islands Isles of Gloom",
"Tolea' Fuin",
"Neverwinter Woods Starlit woods",
"Silmataurea",
"Nightsedge Watchfull City",
"Anthatal",
"Port Llast Ship Dwelling",
"Cairbara",
"Red Larch Red Ridges",
"Caran Pinnath",
"Sewers Stained Water",
"Waenen",
"Southwall",
"Harnram",
"The Lost Hills The Wandering Hills",
"Tel'Ranaemyn",
"Triboar City of Battle",
"Tal Dagore",
"Vilnask Metal Soil",
"Tincokemen",
"Westbridge Dwarf Bridge",
"Naugiaur",
"Windycliffes",
"Sulcabedoo",
" Brotherhood of Pathfinders",
"Toror' Taur'ohtarie",
"Clan Axepeak Flat Metal",
"Laara'tincoras",
"Grey Knights of the Balance Neutral warriors",
"Qualohtarie",
"KAAOS Dark demi-gods",
"Morimaikarea",
"Knights of the Eternal Flame KEF",
"Ohtar en Oionaaru",
"The Black Wind ITB",
"Morsul",
"The Grey Company",
"Tel'Mithrim",
"The Harpers HG",
"Nandaror",
"The Night Masks",
"Tel'Domeduathea",
"The Shadow AllianceThe Grey Shadows",
"Tel'Sindavathar",
"The Sun Guild Sun Champions",
"Tel'Anor Arator",
"Undead Lords UDL",
"Guinahiroo",
" Clumsy",
"Lova tyelka",
"Create Food",
"Onta vasa",
"Feeblemind",
"Lova handasse",
"Heal",
"Tanka harwar",
"Magic Arrow",
"Pilin en' templa",
"Night Sight",
"Elea ie' dome",
"Reactive Armor",
"Atost en' entula orme",
"Weaken",
"Lova poldora",
"Agility",
"Ama tyelka",
"Cunning",
"Ama handasse",
"Cure",
"Poika tuulo' 'kshapsae",
"Harm",
"Tyara harwar",
"Magic Trap",
"Neuma en' templa",
"Magic Untrap",
"Tyela neuma",
"Protection",
"Vara tel' Seldarine",
"Strength",
"Ama poldora",
"Bless",
"Aman tel' Seldarine",
"Fireball",
"Koron en' naur",
"Magic Lock",
"Tangwa en' templa",
"Poison",
"Quanta yassen 'kshapsa",
"Telekinesis",
"Bela ed' templa",
"Teleport",
"Lema ed' templa",
"Unlock",
"Panta tangwa",
"Wall of Stone",
"Ram en' ondo",
"Archcure",
"Poika tel' taurninin",
"Archprotection",
"Vara tel' taurninin",
"Curse",
"Thanga yassen templa",
"Fire Field",
"Ram en' naur",
"Greater Heal",
"Tanka tel' taurnin",
"Lightning",
"Russe tuulo' moriloomir",
"Mana Drain",
"Lova termara en' templa",
"Recall",
"Entula a' moinayamen'",
"Blade Spirits",
"Hyandae en' luhta",
"Dispel Field",
"Men imya ram en' templa",
"Incognito",
"Nurta I' fea",
"Magic Reflection",
"Entula en' templa",
"Mind Blast",
"Pelekta yassen I' handele",
"Paralyze",
"Templa en' tessa",
"Poison Field",
"Ram en' 'kshapsa",
"Summon Creature",
"Yala onna",
"Dispel",
"'Kshonna, wanya",
"Energy Bolt",
"Faina templa",
"Explosion",
"Bragollach en' templa",
"Invisibility",
"Quella tuulo' elea",
"Mark",
"Yulma ten' lemar en' templa",
"Mass Curse",
"Thangarim yassen templa",
"Paralyze Field",
"Ram en' tessa",
"Reveal",
"Elea i'dolen",
"Chain Lightning",
"Tincya en' russe tuulo' moriloomir",
"Energy Field",
"Ram en' templa",
"Flamestrike",
"Pelekta yassen runya",
"Gate Travel",
"Lema ed' ando en' templa",
"Mana Vampire",
"Sana termara en' templa",
"Mass Dispel",
"'Kshonnarim, wanya",
"Meteor Swarm",
"Runyalanta gonea",
"Polymorph",
"Luhta kanta",
"Earthquake",
"Tintila, kemen",
"Energy Vortex",
"Pela en' bela templa",
"Resurrection",
"Entula tuulo' i'ba",
"Summon Air Elemental",
"Yala onna en' vilya",
"Summon Daemon",
"Yala rauko",
"Summon Earth Elemental",
"Yala onna en' kemen",
"Summon Fire Elemental",
"Yala onna en' naur",
"Summon Water Elemental",
"Yala onna en' alu",
" burning hands",
"naar cam",
"charm monster",
"nai uuvanimo turamin",
"charm person",
"nai turamin",
"cloudkill",
"loomi en gurth",
"cone of cold",
"ring wing",
"dimension door",
"irma haeannon",
"dispel magic",
"lietha guldur",
"enlarge",
"bragol alaa",
"fear",
"gorgamin",
"feeblemind",
"amin vasa lle sinta",
"fire shield cold",
"naur tinchor ostring",
"fire shield hot",
"naur tinchor osturra",
"Fireball",
"bragollach tel'llach",
"Haste",
"asca melloneamin",
"hold monster",
"n'tess uuvanimo",
"hold person",
"n'tess gothamin",
"ice storm",
"khelek hurro'",
"invisibility",
"amin quella",
"invisibility 10'",
"lle quella",
"lightning bolt",
"lanta en' kalale",
"Magic missile",
"templa pilini'",
"minor globe",
"pela tanya tempa aiguldur",
"mirror image",
"karn aduamin",
"read magic",
"parm templa tengwa",
"shield",
"tinechor",
"sleep",
"lanta kaima",
"stinking cloud",
"loomi tanya lirva amin",
"strength",
"bragol thalion",
" East",
"Rhun",
"North",
"For",
"South",
"Har",
"West",
"Numen",
" Archmage",
"Val'istar",
"Assassin",
"Sereg'wethrin",
"Bard",
"Lindar",
"Cleric",
"Amandil",
"Druid",
"Taur'amandil",
"Illusionist",
"Ita'istar",
"Paladin",
"Nim'ohtar",
"Ranger",
"Taur'ohtar",
"Thief",
"Cam'wethrin",
"Warrior",
"Ohtar",
"Wizard",
"Istar",
" Centaur",
"Rah'edan",
"Drow Normal",
"Tel'gothrim",
"Drow When indicating respect",
"Mori'quessir",
"Dwarf",
"Naugrim",
"Gnome",
"Nogoth",
"Gnome",
"Nogoth",
"Gray elf",
"Mith'quessir",
"Half-elf",
"Elandili",
"Halfling",
"Peredhil",
"High elf",
"Cala'quessir",
"Human",
"Edan",
"Moon elf",
"Ithil'quessir",
"Orc",
"Glamhoth",
"Sea elf",
"Ear'quessir",
"Silver elf",
"Mith'quessir",
"Sunrise elf",
"Amrun'quessir",
"Sylvan elf",
"Taur'quessir",
" Monday",
"Elenya",
"Tuesday",
"Anarya",
"Wednesday",
"Isilya",
"Thursday",
"Alduya",
"Friday",
"Menelya",
"Saturday",
"Valanya",
"Sunday",
"Tarion",
"  January",
"Narvinye",
"February",
"Nenime",
"March",
"Sulime",
"April",
"Viresse",
"May",
"Lotesse",
"June",
"Narie",
"July",
"Cermie",
"August",
"Urime",
"September",
"Yavannie",
"October",
"Narquelie",
"November",
"Hisime",
"December",
"Ringare",
" Winter Solstice",
"Yenearsira",
"Spring Festival",
"Sheelala",
"Vernal Equinox",
"Ehtele'mele",
"Autumnal Equinox",
"Yavieba",
"Summer Solstace",
"Faradome",
"  Captain",
"Nikerym",
"Lieutenant",
"Shaalth",
"Swordmaster",
"Megiltura",
"Priest",
"Amandil",
"Chronicler",
"Kiirar",
" he",
"ro",
"her, hers",
"he",
"him, his",
"ho",
"I, my, mine",
"amin",
"it, its",
"ta",
"she",
"re",
"that",
"tanya",
"them, their",
"sen",
"they",
"ron",
"this",
"sina",
"we, us, ours",
"lye",
"who",
"ya",
"you, yours",
"lle",
"you, yours plural",
"llie",
" 'Ksherea",
"Evil ones",
"'Kshonna, wanya",
"Dispel",
"'Kshonnarim, wanya",
"Mass Dispel",
"'Quel re amrun undome",
"Good day morning evening",
"A'maelamin",
"My beloved",
"A!",
"Ah!",
"Aa' i'sul nora lanne'lle",
"May the wind fill your sails",
"Aa' lasser en lle coia orn n' omenta gurtha",
"May the leaves of your life tree never turn brown",
"Aa' menealle nauva calen ar' malta",
"May your ways be green and golden",
"Aa' menle nauva calen ar' ta hwesta e' ale'quenle",
"May thy paths be green and the breeze on thy back",
"Aaye",
"Hail",
"Agaryulnaerea",
"Blood-suckers",
"Ai' atar",
"Little father An adult male dwarf",
"Aierea",
"Short ones",
"Aiya!",
// "Oh!",
// "Alduya",
// "Thursday",
// "Ale' amin lye tela sinome",
// "After I we finish here",
// "Ama handasse",
// "Cunning",
// "Ama poldora",
// "Strength",
// "Ama tyelka",
// "Agility",
// "Aman tel' Seldarine",
// "Bless",
// "Amandil",
// "Cleric",
// "Amandil",
// "Priest",
// "amin",
// "I, my, mine",
// "Amin uuma merna ta",
// "I don't want it",
// "Amin anta est kaim",
// "I need to rest sleep",
// "Amin autien rath",
// "I'm going to bed",
// "Amin caela noa n'noa",
// "I have an idea no idea",
// "Amin dele ten' ho he sen",
// "I am worried about him her them",
// "Amin delotha lle",
// "I hate you",
// "Amin fauka",
// "I am thirsty",
// "Amin feuya ten' lle",
// "You disgust me",
// "Amin harmuva onalle e' cormamin",
// "I shall treasure your gift in my heart",
// "Amin hiraetha",
// "I'm sorry",
// "Amin irma fion laure sereg",
// "I would like some wine mead ale",
// "Amin khiluva lle a' gurtha ar' thar",
// "I will follow you to death and beyond",
// "Amin lava",
// "I yield",
// "Amin mela lle",
// "I love you",
// "Amin merna quen",
// "I wish to speak",
// "Amin n'rangwa edanea",
// "I don't understand these humans",
// "Amin naa lle nai",
// "I am yours to command",
// "Amin naa tualle",
// "I am your servant",
// "Amin nauva auta yeste'",
// "I will go first",
// "Amin nowe ron n'kelaya",
// "I thought they would never leave",
// "amin quella",
// "invisibility",
// "Amin saesa",
// "My pleasure",
// "Amin sinta lle?",
// "Do I know you?",
// "Amin sinta thaliolle e dagor",
// "I know your strength in battle",
// "Amin utue ta",
// "I found it",
// "Amin uuma malia",
// "I don't care",
// "amin vasa lle sinta",
// "feeblemind",
// "Amin weera yassen lle",
// "I agree with you",
// "Amrun'quessir",
// "Sunrise elf",
// "An lema?",
// "Long journey?",
// "Anarya",
// "Tuesday",
// "Andodulin",
// "Gate birdslain enemy",
// "Anthatal",
// "Nightsedge Watchfull City",
// "Antolle ulua sulrim",
// "Much wind pours from your mouth",
// "Aratoamin",
// "My champion",
// "Arwen en amin",
// "My lady non familiar",
// "Arwenamin",
// "My lady familiar",
// "Asca",
// "Hurry",
// "asca melloneamin",
// "Haste",
// "Ascarerea",
// "Impetous ones",
// "Astalderea",
// "Valiant ones",
// "Atost en' entula orme",
// "Reactive Armor",
// "Auta miqula orqu",
// "Go kiss an orc",
// "Avarierea",
// "Unwilling ones",
// "Beikaerea",
// "Excessive ones",
// "Bela ed' templa",
// "Telekinesis",
// "Belegerea",
// "Mighty ones",
// "bragol alaa",
// "enlarge",
// "bragol thalion",
// "strength",
// "Bragollach en' templa",
// "Explosion",
// "bragollach tel'llach",
// "Fireball",
// "Caela ie'lle",
// "Have at thee!",
// "Cairbara",
// "Port Llast Ship Dwelling",
// "Cala'quessir",
// "High elf",
// "Cam'wethrin",
// "Thief",
// "Caran Pinnath",
// "Red Larch Red Ridges",
// "Cermie",
// "July",
// "Cormamin lindua ele lle",
// "My heart sings to see thee",
// "Cormamin niuve tenna' ta elea lle au'",
// "My heart shall weep until it sees thee again",
// "Cormlle naa tanya tel'raa",
// "Your heart is that of the lion",
// "Creoso a'baramin",
// "Welcome to my dwelling",
// "Creoso, mellonamin",
// "Welcome my friend",
// "Cuamin linduva yassen megrille",
// "My bow will sing with your sword",
// "Dagnir en taur'ohtar",
// "Berun Ranger's Bane",
// "Desiel?",
// "Ready?",
// "Detholalle",
// "Your choice",
// "Dina",
// "Be silent",
"Dinaerea",
"Silent ones",
"Diola lle",
"Thank you",
"Dolle naa lost",
"Your head is empty",
"Ear'quessir",
"Sea elf",
"Ed' i'ear ar' elenea!",
"By the sea and stars!",
"Edan",
"Human",
"Ehtele'mele",
"Vernal Equinox",
"Ela sen",
"Flank them",
"Elandili",
"Half-elf",
"Elea i'dolen",
"Reveal",
"Elea ie' dome",
"Night Sight",
"Elear",
"Visionary",
"Elen sila lumenn omentilmo",
"A star shall shine on the hour of our meeting",
"Elenya",
"Monday",
"En!",
"Look!",
"Engwarerea",
"Ill ones",
"Entula a' moinayamen'",
"Recall",
"Entula en' templa",
"Magic Reflection",
"Entula tuulo' i'ba",
"Resurrection",
"Esta sinome",
"Rest here",
"Estolada sinome",
"Camp here",
"Faina templa",
"Energy Bolt",
"Faradome",
"Summer Solstace",
"Feuyaerea",
"Disgusting ones",
"For",
"North",
"Gayaerea",
"Dreaded ones",
"Glamhoth",
"Orc",
"Gorgaerea",
"Fearful ones",
"gorgamin",
"fear",
"Goth en gothamin",
"Foe of my foe",
"Gothrimamin",
"My foes",
"Guinahiroo",
"Undead Lords UDL",
"Gurth gothrim Tel' Mithrim",
"Death to the foes of the Grey Company",
"Gurth gothrim Tel'Quessir",
"Death to the foes of the Elves",
"Gurth gothrimlye",
"Death to our foes",
"Hallaerea",
"Tall ones",
"Hama sinome",
"Have a seat",
"Har",
"South",
"Harnram",
"Southwall",
"he",
"her, hers",
"Helkaerea",
"Icy ones",
"Heru en amin",
"My lord non familiar",
"Heruamin",
"My lord familiar",
"Hisime",
"November",
"ho",
"him, his",
"Hodoerea",
"Wise ones",
"Hyandae en' luhta",
"Blade Spirits",
"I'narr en gothrim glinuva nuin I'anor",
"The bones of our foes will gleam under the sun",
"I'quelin Mori'Quessier naa ba Mori'Quessir",
"The best Drow is a dead Drow",
"Ianterea",
"Old ones",
"Iire lye lle auta?",
"When do we you leave?",
"Iire?",
"When?",
"irma haeannon",
"dimension door",
"Isilya",
"Wednesday",
"Istar",
"Wizard",
"Ita'istar",
"Illusionist",
"Ithil'quessir",
"Moon elf",
"karn aduamin",
"mirror image",
"Kela",
"Go away",
"khelek hurro'",
"ice storm",
"Kheleksii",
"Luskan Icy Beach",
"Khila amin",
"Follow me",
"Kiirar",
"Chronicler",
"Koron en' naur",
"Fireball",
"Kotyaerea",
"Hostile ones",
"Kwara sina ten'amin",
"Hold this for me",
"Kwentra lye i'narn",
"Tell us the tale",
"Laara'tincoras",
"Clan Axepeak Flat Metal",
"Lannerea",
"Wide ones",
"lanta en' kalale",
"lightning bolt",
"lanta kaima",
"sleep",
"Lasta lalaithamin",
"Listen to my laughter",
"Lema ed' ando en' templa",
"Gate Travel",
"Lema ed' templa",
"Teleport",
"lietha guldur",
"dispel magic",
"Lindar",
"Bard",
"Lirimaerea",
"Lovely ones",
"Lissenen ar' maska'lalaith tenna' lye omentuva",
"Sweet water and light laughter till next we meet",
"lle",
"you, yours",
"Lle anta amin tu?",
"Do you need help?",
"Lle anta yulna en alu?",
"Do you need a drink of water?",
"Lle auta yeste'",
"You go first",
"Lle creoso",
"You're welcome",
"Lle desiel?",
"Are you ready?",
"Lle holma ve' edan",
"You smell like a human",
"Lle ista amin quella no' amin?",
"Could you cast invis on me?",
"Lle lakwenien?",
"Are you joking?",
"Lle lava?",
"Do you yield?",
"Lle maa quel",
"You look good",
"Lle merna aut farien?",
"Shall we go hunting?",
"Lle merna salk?",
"Do you want to dance?",
"Lle naa belegohtar",
"You are a mighty warrior",
"Lle naa curucuar",
"You are a skillful bowman",
"Lle naa haran e' nausalle",
"You are king in your imagination",
"Lle naa vanima",
"You are beautiful",
"lle quella",
"invisibility 10'",
"Lle quena i'lambe tel' Eldalie?",
"Do you speak elvish?",
"Lle rangwa amin?",
"Do you understand me?",
"Lle tela?",
"Are you finished?",
"Lle tyava quel?",
"Do you feel well?",
"Lle ume quel",
"You did well",
"Lle vesta?",
"Do you promise?",
"Lle wethrine amin",
"You deceived me",
"llie",
"you, yours plural",
"Llie n'vanima ar' lle atara lanneina",
"You're ugly and your mother dresses you funny",
"loomi en gurth",
"cloudkill",
"loomi tanya lirva amin",
"stinking cloud",
"Lotesse",
"May",
"Lova handasse",
"Feeblemind",
"Lova poldora",
"Weaken",
"Lova termara en' templa",
"Mana Drain",
"Lova tyelka",
"Clumsy",
"Luhta kanta",
"Polymorph",
"lye",
"we, us, ours",
"Lye naa lle nai",
"We are yours to command",
"Lye nuquernuva sen e dagor",
"We will defeat them in battle",
"Mae govannen",
"Well met",
"Maien quel n'quel",
"Looking good bad",
"Malia ten' fion laure sereg?",
"Care for some wine mead ale?",
"Malia ten' vasa?",
"Care for some food?",
"Malia ten' yulna?",
"Care for a drink?",
"Mallen pelu e' n'alaquel en' sen",
"Circle around behind them",
"Mani er?",
"Which one?",
"Mani marte?",
"What happened?",
"Mani naa essa en lle?",
"What's your name?",
"Mani naa lle umien?",
"What are you doing?",
"Mani naa ta?",
"What is it?",
"Mani naa tanya nat'?",
"What is that thing?",
"Mani nae lle umien?",
"What have you been doing?",
"Mani uma lle merna ten' ta?",
"What do you want for it?",
"Mani ume lle quena?",
"What did you say?",
"Mani?",
"What?",
"Manka lle merna",
"If you wish",
"Manke naa nae lle llie lye tuulo'?",
"Where are were you you all we from?",
"Manke naa nae lle?",
"Where are were you?",
"Manke naa lye lle autien?",
"Where are we you going?",
"Manke naa i'omentien?",
"Where is the meeting?",
"Manke naa lye omentien?",
"Where are we meeting?",
"Manke tanya tuula?",
"Where did that come from?",
"Manke?",
"Where?",
"Mankoi lle irma sint?",
"Why do you want to know?",
"Mankoi lle uma tanya?",
"Why did you do that?",
"Mankoi naa lle sinome?",
"Why are you here?",
"Mankoi?",
"Why?",
"Megiltura",
"Swordmaster",
"Mela en' coiamin",
"Love of my life",
"Melamin",
"My love",
"Mellon en mellonamin",
"Friend of my friend",
"Mellonea",
"Friends",
"Mellonamin",
"My friend",
"Melloneamin",
"My friends",
"Men imya ram en' templa",
"Dispel Field",
"Menelya",
"Friday",
"Menomenta",
"Crossergate Path Crossing",
"Mereth en draugrim",
"Feast of wolves slain enemy",
"Mith'quessir",
"Gray elf",
"Mith'quessir",
"Silver elf",
"Mori'quessir",
"Drow When indicating respect",
"Morierea",
"Dark ones",
"Morimaikarea",
"KAAOS Dark demi-gods",
"Morsul",
"The Black Wind ITB",
"N'hrive",
"Neverwinter",
"N'ndengina ta ho",
"Don't kill it him",
"n'tess gothamin",
"hold person",
"n'tess uuvanimo",
"hold monster",
"naar cam",
"burning hands",
"Nadorhuanrim",
"Cowardly dogs",
"Nae saian luume'",
"It has been too long",
"nai turamin",
"charm person",
"nai uuvanimo turamin",
"charm monster",
"Namaarie",
"Farewell",
"Nandaror",
"The Harpers HG",
"Narie",
"June",
"Narquelie",
"October",
"Narvinye",
"January",
"Naugiaur",
"Westbridge Dwarf Bridge",
"Naugrim",
"Dwarf",
"naur tinchor ostring",
"fire shield cold",
"naur tinchor osturra",
"fire shield hot",
"Ndengina ta ho",
"Kill it him",
"Nenime",
"February",
"Neuma en' templa",
"Magic Trap",
"Neuma!",
"Trap!",
"Nikerym",
"Captain",
"Nim'ohtar",
"Paladin",
"Nogoth",
"Gnome",
"Nogoth",
"Gnome",
"Nuduin",
"Floodblest Under River",
"Numen",
"West",
"Nurta",
"Hide",
"Nurta I' fea",
"Incognito",
"Nwalmaerea",
"Tormented ones",
"Ohtar",
"Warrior",
"Ohtar en Oionaaru",
"Knights of the Eternal Flame KEF",
"Oio naa elealla alasse'",
"Ever is thy sight a joy",
"Ona ta a'amin",
"Give it to me",
"Onta vasa",
"Create Food",
"Panta tangwa",
"Unlock",
"parm templa tengwa",
"read magic",
"Pela en' bela templa",
"Energy Vortex",
"pela tanya tempa aiguldur",
"minor globe",
"Pelekta yassen I' handele",
"Mind Blast",
"Pelekta yassen runya",
"Flamestrike",
"Peredhil",
"Halfling",
"Pilin en' templa",
"Magic Arrow",
"Poika tel' taurninin",
"Archcure",
"Poika tuulo' 'kshapsae",
"Cure",
"Poikaerea",
"Pure ones",
"Qualohtarie",
"Grey Knights of the Balance Neutral warriors",
"Quanta yassen 'kshapsa",
"Poison",
"Quel andune",
"Good afternoon",
"Quel du",
"Good night",
"Quel esta",
"Rest well",
"Quel fara",
"Good hunting",
"Quel kaima",
"Sleep well",
"Quel lome",
"Good evening Farewell",
"Quel marth",
"Good luck",
"Quel re",
"Good day",
"Quel undome",
"Good evening Greeting",
"Quella tuulo' elea",
"Invisibility",
"Rah'edan",
"Centaur",
"Ram en' 'kshapsa",
"Poison Field",
"Ram en' naur",
"Fire Field",
"Ram en' ondo",
"Wall of Stone",
"Ram en' templa",
"Energy Field",
"Ram en' tessa",
"Paralyze Field",
"re",
"she",
"Re caele beika fion laure sereg",
"She had too much wine mead ale",
"Rhun",
"East",
"Rima ten'ta!",
"Run for it!",
"Rina istorlle sinome",
"Memorize your spells here",
"ring wing",
"cone of cold",
"Ringare",
"December",
"ro",
"he",
"Ro caele beika fion laure sereg",
"He had too much wine mead ale",
"ron",
"they",
"Ron rangwa amin?",
"Do they understand me?",
"Runyalanta gonea",
"Meteor Swarm",
"Russe tuulo' moriloomir",
"Lightning",
"Ruthaerea",
"Angry ones",
"rwalaerea",
"Lusty ones",
"Saesa omentien lle",
"Pleasure meeting you",
"Sana sina",
"Take this",
"Sana termara en' templa",
"Mana Vampire",
"Saurarea",
"Foul ones",
"Seasamin",
"My pleasure",
"sen",
"them, their",
"Sereg'wethrin",
"Assassin",
"Shaalth",
"Lieutenant",
"Sheelala",
"Spring Festival",
"Sii'",
"Now!",
"Silmataurea",
"Neverwinter Woods Starlit woods",
"sina",
"this",
"Soora sen ta",
"Follow them it",
"Spangaerea",
"Bearded ones",
"Sulcabedoo",
"Windycliffes",
"Sulime",
"March",
"Sut an?",
"How long?",
"Sut naa lle umien sina re?",
"How are you doing today?",
"Sut?",
"How?",
"ta",
"it, its",
"Ta naa nae seasamin",
"It is was my pleasure",
"Ta naa neuma!",
"It is a trap!",
"Ta naa seasamin",
"It is my pleasure",
"Tal Dagore",
"Triboar City of Battle",
"Tampa tanya!",
"Stop that!",
"Tangwa en' templa",
"Magic Lock",
"Tanka harwar",
"Heal",
"Tanka tel' taurnin",
"Greater Heal",
"tanya",
"that",
"Tanya awra!",
"That hurt!",
"Tanya farnuva",
"That will suffice",
"Tanya nae sai eina",
"That was very funny",
"Tanya nae n'quel",
"That was not good",
"Taraerea",
"Lofty ones",
"Tarion",
"Sunday",
"Taur'amandil",
"Druid",
"Taur'ohtar",
"Ranger",
"Taur'quessir",
"Sylvan elf",
"Tel'Anor Arator",
"The Sun Guild Sun Champions",
"Tel'Domeduathea",
"The Night Masks",
"Tel'Mithrim",
"The Grey Company",
"Tel'Ranaemyn",
"The Lost Hills The Wandering Hills",
"Tel'Sindavathar",
"The Shadow AllianceThe Grey Shadows",
"Tel'gothrim",
"Drow Normal",
"Telcoerea",
"Stern ones",
"Templa en' tessa",
"Paralyze",
"templa pilini'",
"Magic missile",
"Tenna' ento lye omenta",
"Until next we meet",
"Tenna' san'",
"Until then",
"Tenna' telwan san'",
"Until later then",
"Tenna' tul're san'",
"Until tomorrow then",
"Tessa sina ten' amin",
"Hold onto this for me",
"Thanga yassen templa",
"Curse",
"Thangarim yassen templa",
"Mass Curse",
"Thaurerea",
"Abominable ones",
"Tincokemen",
"Vilnask Metal Soil",
"Tincya en' russe tuulo' moriloomir",
"Chain Lightning",
"tinechor",
"shield",
"Tintila, kemen",
"Earthquake",
"Tira ten' rashwe!",
"Look out   Be carefull!",
"Tolea' Fuin",
"Neverwinter Islands Isles of Gloom",
"Toror' Taur'ohtarie",
"Brotherhood of Pathfinders",
"Tua amin!",
"Help me!",
"Tula Uialtum",
"Come to Longsaddle",
"Tula sinome",
"Come here",
"Tula, hama neva i'naur",
"Come, sit near the fire",
"Tula, vasa ar' yulna en i'mereth",
"Come, eat and drink of the feast",
"Tulien",
"Coming",
"Tyara harwar",
"Harm",
"Tyela neuma",
"Magic Untrap",
"Uialtum",
"Longsaddle Twilight Valley",
"Unguerea",
"Hollow ones",
"Urime",
"August",
"Usquenerea",
"Smelly ones",
"Utinu en lokirim",
"Son of snakes dishonest person",
"Uuma dela",
"Don't worry",
"Uuma ma' ten' rashwe, ta tuluva a' lle",
"Don't look for trouble, it will come to you",
"Uuner uma, n'dela no'ta",
"No one does, don't worry about it",
"Val'istar",
"Archmage",
"Valanya",
"Saturday",
"Vanimle sila tiri",
"Your beauty shines bright",
"Vanya sulie",
"Fair winds",
"Vara tel' Seldarine",
"Protection",
"Vara tel' taurninin",
"Archprotection",
"Vedui' il'er",
"Greetings everyone",
"Viresse",
"April",
"Voronwerea",
"Loyal ones",
"Waenen",
"Sewers Stained Water",
"Wethrinaerea",
"Deceitfull ones",
"Ya naa nae tanya?",
"Who is was that?",
"Ya auta yeste'?",
"Who's leading?",
"Ya?",
"Who?",
"Yaaraerea",
"Ancient ones",
"Yala onna",
"Summon Creature",
"Yala onna en' alu",
"Summon Water Elemental",
"Yala onna en' kemen",
"Summon Earth Elemental",
"Yala onna en' naur",
"Summon Fire Elemental",
"Yala onna en' vilya",
"Summon Air Elemental",
"Yala rauko",
"Summon Daemon",
"Yallume",
"At last!",
"Yavannie",
"September",
"Yavieba",
"Autumnal Equinox",
"Yee!",
"Eek!",
"Yenearsira",
"Winter Solstice",
"Yulma ten' lemar en' templa",
"Mark",];

  var sayings = [];
  var meanings = [];

  for (var i =0; i < elvishSayingsAndMeanings.length;i++) {
  	var thing = elvishSayingsAndMeanings[i];
  	if (i % 2) {
  		sayings.push(elvishSayingsAndMeanings[i]);
  	} else {
  		meanings.push(elvishSayingsAndMeanings[i]);
  	}
  };

  var sayingPairs = _.zip(sayings,meanings);

  $scope.run = function(paragraphCount) {

  	console.log("Running!");

  	var sentencesPerParagraph = 12;

  	paragraphCount = paragraphCount || 10;
  	$scope.paragraphs = [];
  	for (var i = 0; i < paragraphCount; i++ ) {
  		var paragraph = [];
  		for (var j = sentencesPerParagraph - 1; j >= 0; j--) {
  			var sentence = _.sample(sayingPairs);
  			paragraph.push(sentence);
  		};

  		paragraph = _.uniq(paragraph);

  		$scope.paragraphs.push(paragraph);
  	}

  	return _.sample(sayings,15).join(" ");
  };

  $scope.run();





}]);